FROM httpd:2.4

COPY http/sites/  /usr/local/apache2/htdocs/
COPY http/decoy.conf /usr/local/apache2/conf/extra/decoy.conf

RUN sed -i 's|^#\?ServerName.*|ServerName corp-server-01|' /usr/local/apache2/conf/httpd.conf \
 && echo "Include conf/extra/decoy.conf" >> /usr/local/apache2/conf/httpd.conf \
 && sed -i 's|^ServerTokens.*|ServerTokens Full|' /usr/local/apache2/conf/httpd.conf || true

EXPOSE 80
