listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=YES
local_enable=YES
write_enable=NO
xferlog_enable=YES
xferlog_file=/var/log/vsftpd/vsftpd.log
xferlog_std_format=NO
log_ftp_protocol=YES
dual_log_enable=YES
vsftpd_log_file=/var/log/vsftpd/vsftpd.log
ftpd_banner=corp-ftp-01 FTP server (vsftpd 3.0.5) ready.
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO
secure_chroot_dir=/var/run/vsftpd/empty
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
# pasv_address artik sabit kodlu degil — entrypoint.sh, FTP_PASV_ADDRESS
# ortam degiskeni doluysa calisma aninda ekler. Bos ise vsftpd otomatik belirler.
port_enable=NO
pam_service_name=vsftpd
