ServerSignature On

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog /usr/local/apache2/logs/access.log combined
ErrorLog  /usr/local/apache2/logs/error.log

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<Files ".env">
    Require all granted
</Files>

<Files "backup.zip">
    Require all granted
</Files>
